workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 10
        working_directory: AbsolutReader
        environment:
            node: latest
        scripts:
            - name: Install npm dependencies
              script: |
                npm install

            - name: Build Android APK
              script: |
                cd android && ./gradlew assembleDebug
        artifacts:
            - android/app/build/outputs/**/*.apk