workflows:
    react-native-android:
      name: React Native Android
      max_build_duration: 10
      working_directory: AbsolutReader
      environment:
          node: latest
      scripts:
        
        - name: Install npm dependencies
          script: |
            npm install

        - name: Set Android SDK location
          script: |
            echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/AbsolutReader/android/local.properties"

        - name: Show dir
          script: |
            ls

        - name: Build Android APK
          script: |
            cd $FCI_BUILD_DIR/AbsolutReader/android && bash ./gradlew assembleDebug

      artifacts:
          - android/app/build/outputs/**/*.apk
      cache:
        cache_paths:
          - $HOME/.gradle/caches
          - $FCI_BUILD_DIR/node_modules
