workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 10
        working_directory: AbsolutReader
        environment:
            node: latest
        scripts:
            - name: Install npm dependencies
              script: |
                npm install

            - name: Build Android APK
              script: |
                echo ls && cd android && ./gradlew assembleDebug
        cache:
          cachepaths:
            - $HOME/.gradle/caches
            - $FCI_BUILD_DIR/node_modules	
        artifacts:
            - android/app/build/outputs/**/*.apk
