workflows:
  android:
    scripts:
      - name: Android APK build.
        working_directory: AbsolutReader/android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
    cache:
          cache_paths:
            - AbsolutReader/node_modules
