// AutolinkedNativeModules.g.cpp contents generated by "react-native autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @react-native-community/progress-view
#include <winrt/progress_view.h>

// Includes from react-native-pdf
#include <winrt/RCTPdf.h>

// Includes from react-native-permissions
#include <winrt/RNPermissions.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @react-native-community/progress-view
    packageProviders.Append(winrt::progress_view::ReactPackageProvider());
    // IReactPackageProviders from react-native-pdf
    packageProviders.Append(winrt::RCTPdf::ReactPackageProvider());
    // IReactPackageProviders from react-native-permissions
    packageProviders.Append(winrt::RNPermissions::ReactPackageProvider());
}

}
