# Generated by Django 3.2.6 on 2021-09-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_donation_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ammount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='donation',
            name='kofi_transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
